// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Feed struct {
	PublishDate string  `json:"publishDate"`
	Text        string  `json:"text"`
	Title       string  `json:"title"`
	Subtitle    string  `json:"subtitle"`
	Description string  `json:"description"`
	Image       *string `json:"image"`
	Summary     string  `json:"summary"`
	LinkURL     string  `json:"linkURL"`
	Duration    string  `json:"duration"`
}

type Podcast struct {
	Artist        string   `json:"artist"`
	Name          string   `json:"name"`
	FeedURL       string   `json:"feedURL"`
	Thumbnail     string   `json:"thumbnail"`
	EpisodesCount int      `json:"episodesCount"`
	Genres        []string `json:"genres"`
}
